#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@ispapp[-1]
	add ucitrack ispapp
	set ucitrack.@ispapp[-1].init=ispapp
	commit ucitrack
EOF

/etc/init.d/ispapp enable
/etc/init.d/ispapp reload
rm -f /tmp/luci-indexcache
exit 0