#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@ispapp[-1]
	add ucitrack ispapp
	set ucitrack.@ispapp[-1].init=ispapp
	commit ucitrack
EOF

chmod +x /etc/init.d/ispapp
chmod +x /bin/ispappd
chmod +x /usr/libexec/rpcd/ispapp
/etc/init.d/ispapp enable
/etc/init.d/ispapp reload
rm -f /tmp/luci-indexcache
exit 0